services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - MYSQL_DATABASE=$MYSQL_DATABASE
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - inception
    ports:
      - "3306:3306"
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"
    env_file:
      - .env
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/arvoyer/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/arvoyer/data/mariadb'

networks:
  inception:
    driver: bridge